name: Cloud DevOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      TF_VAR_allowed_ssh_cidr: "203.0.113.10/32"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: 03-terraform
        run: terraform fmt -check -recursive

      - name: Terraform Init (no backend)
        working-directory: 03-terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: 03-terraform
        run: terraform validate


  ansible:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Ansible Playbook Syntax Check
        working-directory: 04-ansible
        run: ansible-playbook playbooks/sysmonitor.yml --syntax-check
